# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 817e719c2db057dcc9376cedbaf36992b8a79ec542e680ac5f57fd37049c8d9c968a3cdf260888303c00e7f1195104e49eea6e1ebb9d66c17abacbda563f6be5

test:
  secret_key_base: 125d32422064831edb74b495e794108de5c83049ec2bfb35cd587a7eec4f857b3ad0c49e7293507158b6137679b9f76a962a77afc446cd43d4db5877ffd9ae9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
